### ISSUE TITLE
Stop current lein tasks when exiting

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cljsbuild-ui#17]
Might handle this in cljsbuild-ui/app.js in `onWindowClose`

**Comment by oakmac** [comment]
This is working on Linux, would be great if someone could confirm on Mac and Windows. @LesleyMdCampo and @comamitc perhaps?

Steps:
1. run the app
2. start compiling some projects
3. close the program while the projects are still compiling
4. check Task Manager (or equivalent) to make sure there are no zombie java processes still running

**Comment by oakmac** [comment]
This isn't fixed yet; just found a race condition when there are more than one processes running. Will try to fix it later today.

**Comment by oakmac** [comment]
This should be fixed now.

**Comment by oakmac** [comment]
Tested on Mac, Windows, and Linux.
