### ISSUE TITLE
Create new project

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cljsbuild-ui#20]
Since we are touting this as a beginner's tool that makes leiningen invisible, we need to be able to run `lein new mies` or some variant to create projects, not just adding existing projects.

**Comment by oakmac** [comment]
Still a few punchlist items before this is complete:

- [ ] put focus on new project input field when going to that step
- [ ] press enter on new project input field should work
- [ ] input validation of new project folder

**Comment by oakmac** [comment]
Needs testing on Mac and Windows.

**Comment by LesleyMdCampo** [comment]
On a Mac: pressing enter and input validation working. I am getting a cursor in the new project input field, but no outline.

**Comment by oakmac** [comment]
Works on Windows
