### ISSUE TITLE
Installing in 64 bit Windows 7 

### ISSUE THREAD

**Issue by simax** [oakmac/cljsbuild-ui#29]
I have node version v0.10.21 and npm version 1.3.11 installed on 64 bit windows 7

I followed the install instructions, apart from running ./build-lein-profile-tool.sh which doesn't work in windows (this version of windows doesn't understand **cp**) So I ran the commands contained in this file individually. 

Everything ran without error.  When I run launch.bat I just get a new completely empty window. 

Am I doing something wrong?

**Comment by shaunlebron** [comment]
we need to streamline all those setup steps for sure... But I usually get a blank window if I forget to run `lein cljsbuild auto`.  And make sure to copy `app/example.config.json` to `app/config.json`.  After doing that, you should be able to see console errors in the dev-tools pane.

**Comment by simax** [comment]
I've just gone through all the steps again including ```lein cljsbuild auto``` (in fact I did ```lein cljsbuild once```). and copying ```app\example.config.json``` to ```app\config.json``` but I still get an empty window (although the chrome dev-tools now appear as you suggested, but with no errors listed. I'm going to try it all again on a windows 8.1 box I have access to. I let you know the results of that experiment.

**Comment by simax** [comment]
Rather than using windows 8.1 I first had a try on Yosemite on my macbook pro.

node version: v0.10.35
npm version: 1.4.28 

After cloning the repo I issued the following commands, all completed successfully 

npm install
npm install -g grunt-cli
npm install -g winresourcer
grunt curl
grunt download-atom-shell
./build-lein-profile-tool.sh
grunt less
lein cljsbuild once
./launch.sh

... and I ended up with a blank window. 
Anybody any thoughts on what I try next?

**Comment by shaunlebron** [comment]
Thanks for your patience and step details.  We were able to reproduce this on a windows machine; looking into it.

**Comment by oakmac** [comment]
Thank you for your detailed report :)

I don't think this problem was specific to Windows; I was able to reproduce on Linux with a fresh clone.

See if commit bfc5d07 fixed it for you?

**Comment by comamitc** [comment]
Fixed my identical behavior that @simax was seeing on a Mac.

:+1:

**Comment by simax** [comment]
Yeah, I can now see the UI. Thanks for the fix guys.
