### ISSUE TITLE
Package up installation steps

### ISSUE THREAD

**Issue by comamitc** [oakmac/cljsbuild-ui#31]
Currently you need to run ~9 one-liners in the terminal to setup the project and run it.  It would be nice to migrate to one `setup.{sh,bat}` script or some other minimal solution.

**Comment by oakmac** [comment]
Agree. We should be able to do most of it with Grunt pretty easily.

Something like `grunt dev-setup` should get you 99% of the way there.

**Comment by oakmac** [comment]
Are we calling this good with commit c61da3a0fbbaadb7254212f6df7b77e89f399ef2?

@shaunlebron

**Comment by shaunlebron** [comment]
I need to test this on windows first.  Will do that tonight.
