### ISSUE TITLE
check for valid JDK on startup

### ISSUE THREAD

**Issue by oakmac** [oakmac/cljsbuild-ui#43]
We need to check for the existence of Java (which version?) on startup and show an error message if it does not exist.

**Comment by oakmac** [comment]
We do not need to ship Java with the build tool; people can figure that part out on their own.

**Comment by shaunlebron** [comment]
- [ClojureScript requires Java 7+](https://twitter.com/swannodette/status/553249970430943234)
- [Clojure does not require JDK, just the JRE](http://stackoverflow.com/questions/4807460/does-clojure-require-a-jdk)

Screenshot of page when java is not installed:
![screen shot 2015-01-15 at 3 15 13 am](https://cloud.githubusercontent.com/assets/116838/5755070/dc771536-9c65-11e4-9565-3a559d903b75.png)
