### ISSUE TITLE
add loading state for projects that need to load using Lein profiles

### ISSUE THREAD

**Issue by oakmac** [oakmac/cljsbuild-ui#44]
Adding projects that depend on Leiningen profiles right now is pretty slow and happens asynchronously.

We should display a "loading..." state for those projects that are loading so the user knows what's going on.

**Comment by shaunlebron** [comment]
Screenshot of project loading profile info:
![lein-profile-loading](https://cloud.githubusercontent.com/assets/116838/5755106/39887ab2-9c66-11e4-87c4-e9d16bcaf22f.png)
